// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/atlantis_agent.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_StreamJobs_FullMethodName      = "/atlantis.agent.AgentService/StreamJobs"
	AgentService_ReportJobStatus_FullMethodName = "/atlantis.agent.AgentService/ReportJobStatus"
	AgentService_GetJob_FullMethodName          = "/atlantis.agent.AgentService/GetJob"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the gRPC service for master-agent communication
type AgentServiceClient interface {
	// StreamJobs is a bidirectional stream where agents send messages
	// (registration, heartbeats, results) and receive job assignments
	StreamJobs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, JobAssignment], error)
	// ReportJobStatus allows agents to report status updates
	ReportJobStatus(ctx context.Context, in *JobStatusUpdate, opts ...grpc.CallOption) (*Ack, error)
	// GetJob retrieves job details by ID (alternative to streaming)
	GetJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobDetails, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) StreamJobs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, JobAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, JobAssignment]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamJobsClient = grpc.BidiStreamingClient[AgentMessage, JobAssignment]

func (c *agentServiceClient) ReportJobStatus(ctx context.Context, in *JobStatusUpdate, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AgentService_ReportJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobDetails)
	err := c.cc.Invoke(ctx, AgentService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the gRPC service for master-agent communication
type AgentServiceServer interface {
	// StreamJobs is a bidirectional stream where agents send messages
	// (registration, heartbeats, results) and receive job assignments
	StreamJobs(grpc.BidiStreamingServer[AgentMessage, JobAssignment]) error
	// ReportJobStatus allows agents to report status updates
	ReportJobStatus(context.Context, *JobStatusUpdate) (*Ack, error)
	// GetJob retrieves job details by ID (alternative to streaming)
	GetJob(context.Context, *JobRequest) (*JobDetails, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) StreamJobs(grpc.BidiStreamingServer[AgentMessage, JobAssignment]) error {
	return status.Error(codes.Unimplemented, "method StreamJobs not implemented")
}
func (UnimplementedAgentServiceServer) ReportJobStatus(context.Context, *JobStatusUpdate) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJobStatus not implemented")
}
func (UnimplementedAgentServiceServer) GetJob(context.Context, *JobRequest) (*JobDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_StreamJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StreamJobs(&grpc.GenericServerStream[AgentMessage, JobAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamJobsServer = grpc.BidiStreamingServer[AgentMessage, JobAssignment]

func _AgentService_ReportJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportJobStatus(ctx, req.(*JobStatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlantis.agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportJobStatus",
			Handler:    _AgentService_ReportJobStatus_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _AgentService_GetJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobs",
			Handler:       _AgentService_StreamJobs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/atlantis_agent.proto",
}
