// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/atlantis_agent.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage represents messages sent from agent controller to master
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_Registration
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_JobResult
	//	*AgentMessage_CapacityUpdate
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *AgentMessage) GetCapacityUpdate() *CapacityUpdate {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_CapacityUpdate); ok {
			return x.CapacityUpdate
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Registration struct {
	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,3,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type AgentMessage_CapacityUpdate struct {
	CapacityUpdate *CapacityUpdate `protobuf:"bytes,4,opt,name=capacity_update,json=capacityUpdate,proto3,oneof"`
}

func (*AgentMessage_Registration) isAgentMessage_Message() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Message() {}

func (*AgentMessage_JobResult) isAgentMessage_Message() {}

func (*AgentMessage_CapacityUpdate) isAgentMessage_Message() {}

// Registration message for agent controller initial connection
type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControllerId  string                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`                                           // Unique ID for this controller
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                                                             // Authentication token
	ClusterName   string                 `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`                                              // Kubernetes cluster name
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                                     // K8s namespace for agents
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Labels for job routing
	Capacity      int32                  `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`                                                                      // Max concurrent jobs
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`                                                                         // Atlantis version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Registration) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *Registration) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Registration) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Registration) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Registration) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Registration) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Registration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Heartbeat message to maintain connection and report health
type Heartbeat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ControllerId      string                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	CurrentJobs       int32                  `protobuf:"varint,2,opt,name=current_jobs,json=currentJobs,proto3" json:"current_jobs,omitempty"`                   // Currently executing jobs
	AvailableCapacity int32                  `protobuf:"varint,3,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"` // Available slots
	Timestamp         int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                          // Unix timestamp
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *Heartbeat) GetCurrentJobs() int32 {
	if x != nil {
		return x.CurrentJobs
	}
	return 0
}

func (x *Heartbeat) GetAvailableCapacity() int32 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// JobResult message when job completes
type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                   // completed, failed, timeout
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`                                   // Human-readable output
	PlanData      []byte                 `protobuf:"bytes,4,opt,name=plan_data,json=planData,proto3" json:"plan_data,omitempty"`               // Terraform plan binary (for plan commands)
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`              // Terraform exit code
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`   // Error details if failed
	AgentPodName  string                 `protobuf:"bytes,7,opt,name=agent_pod_name,json=agentPodName,proto3" json:"agent_pod_name,omitempty"` // Pod that executed the job
	StartedAt     int64                  `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`           // Unix timestamp
	CompletedAt   int64                  `protobuf:"varint,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`     // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{3}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResult) GetPlanData() []byte {
	if x != nil {
		return x.PlanData
	}
	return nil
}

func (x *JobResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobResult) GetAgentPodName() string {
	if x != nil {
		return x.AgentPodName
	}
	return ""
}

func (x *JobResult) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *JobResult) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

// CapacityUpdate for dynamic capacity changes
type CapacityUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControllerId  string                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	NewCapacity   int32                  `protobuf:"varint,2,opt,name=new_capacity,json=newCapacity,proto3" json:"new_capacity,omitempty"` // Updated capacity
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                               // Why capacity changed (e.g., "draining")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityUpdate) Reset() {
	*x = CapacityUpdate{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityUpdate) ProtoMessage() {}

func (x *CapacityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityUpdate.ProtoReflect.Descriptor instead.
func (*CapacityUpdate) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CapacityUpdate) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *CapacityUpdate) GetNewCapacity() int32 {
	if x != nil {
		return x.NewCapacity
	}
	return 0
}

func (x *CapacityUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// JobAssignment sent from master to agent controller
type JobAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RepoFullName   string                 `protobuf:"bytes,2,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`       // e.g., "owner/repo"
	RepoCloneUrl   string                 `protobuf:"bytes,3,opt,name=repo_clone_url,json=repoCloneUrl,proto3" json:"repo_clone_url,omitempty"`       // Full clone URL
	PullNum        int32                  `protobuf:"varint,4,opt,name=pull_num,json=pullNum,proto3" json:"pull_num,omitempty"`                       // PR number
	PullBranch     string                 `protobuf:"bytes,5,opt,name=pull_branch,json=pullBranch,proto3" json:"pull_branch,omitempty"`               // PR source branch
	PullBaseBranch string                 `protobuf:"bytes,6,opt,name=pull_base_branch,json=pullBaseBranch,proto3" json:"pull_base_branch,omitempty"` // PR target branch
	PullCommitSha  string                 `protobuf:"bytes,7,opt,name=pull_commit_sha,json=pullCommitSha,proto3" json:"pull_commit_sha,omitempty"`    // PR HEAD commit
	Command        string                 `protobuf:"bytes,8,opt,name=command,proto3" json:"command,omitempty"`                                       // plan, apply, unlock
	Workspace      string                 `protobuf:"bytes,9,opt,name=workspace,proto3" json:"workspace,omitempty"`                                   // Terraform workspace
	ProjectName    string                 `protobuf:"bytes,10,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`           // Project name
	ProjectDir     string                 `protobuf:"bytes,11,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`              // Relative path in repo
	PlanData       []byte                 `protobuf:"bytes,12,opt,name=plan_data,json=planData,proto3" json:"plan_data,omitempty"`                    // For apply: the plan to apply
	// VCS credentials for cloning
	VcsCredentials *VCSCredentials `protobuf:"bytes,13,opt,name=vcs_credentials,json=vcsCredentials,proto3" json:"vcs_credentials,omitempty"`
	// Environment variables
	EnvVars map[string]string `protobuf:"bytes,14,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Custom workflow (if any)
	Workflow *WorkflowConfig `protobuf:"bytes,15,opt,name=workflow,proto3" json:"workflow,omitempty"`
	// Terraform version
	TerraformVersion string `protobuf:"bytes,16,opt,name=terraform_version,json=terraformVersion,proto3" json:"terraform_version,omitempty"`
	// Additional metadata
	Metadata map[string]string `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timeout in seconds
	TimeoutSeconds int32 `protobuf:"varint,18,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Serialized ProjectContext for full execution environment reconstruction
	ProjectContextJson []byte `protobuf:"bytes,19,opt,name=project_context_json,json=projectContextJson,proto3" json:"project_context_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{5}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *JobAssignment) GetRepoCloneUrl() string {
	if x != nil {
		return x.RepoCloneUrl
	}
	return ""
}

func (x *JobAssignment) GetPullNum() int32 {
	if x != nil {
		return x.PullNum
	}
	return 0
}

func (x *JobAssignment) GetPullBranch() string {
	if x != nil {
		return x.PullBranch
	}
	return ""
}

func (x *JobAssignment) GetPullBaseBranch() string {
	if x != nil {
		return x.PullBaseBranch
	}
	return ""
}

func (x *JobAssignment) GetPullCommitSha() string {
	if x != nil {
		return x.PullCommitSha
	}
	return ""
}

func (x *JobAssignment) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobAssignment) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *JobAssignment) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *JobAssignment) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *JobAssignment) GetPlanData() []byte {
	if x != nil {
		return x.PlanData
	}
	return nil
}

func (x *JobAssignment) GetVcsCredentials() *VCSCredentials {
	if x != nil {
		return x.VcsCredentials
	}
	return nil
}

func (x *JobAssignment) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *JobAssignment) GetWorkflow() *WorkflowConfig {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *JobAssignment) GetTerraformVersion() string {
	if x != nil {
		return x.TerraformVersion
	}
	return ""
}

func (x *JobAssignment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *JobAssignment) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *JobAssignment) GetProjectContextJson() []byte {
	if x != nil {
		return x.ProjectContextJson
	}
	return nil
}

// VCS credentials for repository access
type VCSCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VcsType       string                 `protobuf:"bytes,1,opt,name=vcs_type,json=vcsType,proto3" json:"vcs_type,omitempty"` // github, gitlab, bitbucket, etc.
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`              // VCS username
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                    // VCS token or password
	SshKey        string                 `protobuf:"bytes,4,opt,name=ssh_key,json=sshKey,proto3" json:"ssh_key,omitempty"`    // SSH private key (if using SSH)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VCSCredentials) Reset() {
	*x = VCSCredentials{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VCSCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCSCredentials) ProtoMessage() {}

func (x *VCSCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCSCredentials.ProtoReflect.Descriptor instead.
func (*VCSCredentials) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{6}
}

func (x *VCSCredentials) GetVcsType() string {
	if x != nil {
		return x.VcsType
	}
	return ""
}

func (x *VCSCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VCSCredentials) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VCSCredentials) GetSshKey() string {
	if x != nil {
		return x.SshKey
	}
	return ""
}

// Workflow configuration for custom workflows
type WorkflowConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanSteps     []*WorkflowStep        `protobuf:"bytes,1,rep,name=plan_steps,json=planSteps,proto3" json:"plan_steps,omitempty"`
	ApplySteps    []*WorkflowStep        `protobuf:"bytes,2,rep,name=apply_steps,json=applySteps,proto3" json:"apply_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowConfig) Reset() {
	*x = WorkflowConfig{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowConfig) ProtoMessage() {}

func (x *WorkflowConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowConfig.ProtoReflect.Descriptor instead.
func (*WorkflowConfig) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowConfig) GetPlanSteps() []*WorkflowStep {
	if x != nil {
		return x.PlanSteps
	}
	return nil
}

func (x *WorkflowConfig) GetApplySteps() []*WorkflowStep {
	if x != nil {
		return x.ApplySteps
	}
	return nil
}

// Individual workflow step
type WorkflowStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`       // init, plan, apply, run
	RunCommand    string                 `protobuf:"bytes,2,opt,name=run_command,json=runCommand,proto3" json:"run_command,omitempty"` // For custom run steps
	ExtraArgs     map[string]string      `protobuf:"bytes,3,rep,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowStep) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *WorkflowStep) GetRunCommand() string {
	if x != nil {
		return x.RunCommand
	}
	return ""
}

func (x *WorkflowStep) GetExtraArgs() map[string]string {
	if x != nil {
		return x.ExtraArgs
	}
	return nil
}

// JobStatusUpdate for intermediate status reports
type JobStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                   // queued, assigned, running, completed, failed
	AgentPodName  string                 `protobuf:"bytes,3,opt,name=agent_pod_name,json=agentPodName,proto3" json:"agent_pod_name,omitempty"` // Pod executing the job
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                 // Status message
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusUpdate) Reset() {
	*x = JobStatusUpdate{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusUpdate) ProtoMessage() {}

func (x *JobStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusUpdate.ProtoReflect.Descriptor instead.
func (*JobStatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{9}
}

func (x *JobStatusUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusUpdate) GetAgentPodName() string {
	if x != nil {
		return x.AgentPodName
	}
	return ""
}

func (x *JobStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobStatusUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// JobRequest to fetch job details
type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{10}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// JobDetails response
type JobDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *JobAssignment         `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDetails) Reset() {
	*x = JobDetails{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetails) ProtoMessage() {}

func (x *JobDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetails.ProtoReflect.Descriptor instead.
func (*JobDetails) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{11}
}

func (x *JobDetails) GetAssignment() *JobAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *JobDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobDetails) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Ack for acknowledgements
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SyncJobsRequest to query for assigned jobs
type SyncJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControllerId  string                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"` // Agent controller ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncJobsRequest) Reset() {
	*x = SyncJobsRequest{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJobsRequest) ProtoMessage() {}

func (x *SyncJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJobsRequest.ProtoReflect.Descriptor instead.
func (*SyncJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{13}
}

func (x *SyncJobsRequest) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

// SyncJobsResponse with list of assigned jobs
type SyncJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobAssignment       `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"` // Jobs assigned to this agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncJobsResponse) Reset() {
	*x = SyncJobsResponse{}
	mi := &file_proto_atlantis_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJobsResponse) ProtoMessage() {}

func (x *SyncJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlantis_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJobsResponse.ProtoReflect.Descriptor instead.
func (*SyncJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_atlantis_agent_proto_rawDescGZIP(), []int{14}
}

func (x *SyncJobsResponse) GetJobs() []*JobAssignment {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_proto_atlantis_agent_proto protoreflect.FileDescriptor

const file_proto_atlantis_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/atlantis_agent.proto\x12\x0eatlantis.agent\"\x9f\x02\n" +
	"\fAgentMessage\x12B\n" +
	"\fregistration\x18\x01 \x01(\v2\x1c.atlantis.agent.RegistrationH\x00R\fregistration\x129\n" +
	"\theartbeat\x18\x02 \x01(\v2\x19.atlantis.agent.HeartbeatH\x00R\theartbeat\x12:\n" +
	"\n" +
	"job_result\x18\x03 \x01(\v2\x19.atlantis.agent.JobResultH\x00R\tjobResult\x12I\n" +
	"\x0fcapacity_update\x18\x04 \x01(\v2\x1e.atlantis.agent.CapacityUpdateH\x00R\x0ecapacityUpdateB\t\n" +
	"\amessage\"\xbd\x02\n" +
	"\fRegistration\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12@\n" +
	"\x06labels\x18\x05 \x03(\v2(.atlantis.agent.Registration.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bcapacity\x18\x06 \x01(\x05R\bcapacity\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\tHeartbeat\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\x12!\n" +
	"\fcurrent_jobs\x18\x02 \x01(\x05R\vcurrentJobs\x12-\n" +
	"\x12available_capacity\x18\x03 \x01(\x05R\x11availableCapacity\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x99\x02\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\tplan_data\x18\x04 \x01(\fR\bplanData\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12$\n" +
	"\x0eagent_pod_name\x18\a \x01(\tR\fagentPodName\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\t \x01(\x03R\vcompletedAt\"p\n" +
	"\x0eCapacityUpdate\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\x12!\n" +
	"\fnew_capacity\x18\x02 \x01(\x05R\vnewCapacity\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xaf\a\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12$\n" +
	"\x0erepo_full_name\x18\x02 \x01(\tR\frepoFullName\x12$\n" +
	"\x0erepo_clone_url\x18\x03 \x01(\tR\frepoCloneUrl\x12\x19\n" +
	"\bpull_num\x18\x04 \x01(\x05R\apullNum\x12\x1f\n" +
	"\vpull_branch\x18\x05 \x01(\tR\n" +
	"pullBranch\x12(\n" +
	"\x10pull_base_branch\x18\x06 \x01(\tR\x0epullBaseBranch\x12&\n" +
	"\x0fpull_commit_sha\x18\a \x01(\tR\rpullCommitSha\x12\x18\n" +
	"\acommand\x18\b \x01(\tR\acommand\x12\x1c\n" +
	"\tworkspace\x18\t \x01(\tR\tworkspace\x12!\n" +
	"\fproject_name\x18\n" +
	" \x01(\tR\vprojectName\x12\x1f\n" +
	"\vproject_dir\x18\v \x01(\tR\n" +
	"projectDir\x12\x1b\n" +
	"\tplan_data\x18\f \x01(\fR\bplanData\x12G\n" +
	"\x0fvcs_credentials\x18\r \x01(\v2\x1e.atlantis.agent.VCSCredentialsR\x0evcsCredentials\x12E\n" +
	"\benv_vars\x18\x0e \x03(\v2*.atlantis.agent.JobAssignment.EnvVarsEntryR\aenvVars\x12:\n" +
	"\bworkflow\x18\x0f \x01(\v2\x1e.atlantis.agent.WorkflowConfigR\bworkflow\x12+\n" +
	"\x11terraform_version\x18\x10 \x01(\tR\x10terraformVersion\x12G\n" +
	"\bmetadata\x18\x11 \x03(\v2+.atlantis.agent.JobAssignment.MetadataEntryR\bmetadata\x12'\n" +
	"\x0ftimeout_seconds\x18\x12 \x01(\x05R\x0etimeoutSeconds\x120\n" +
	"\x14project_context_json\x18\x13 \x01(\fR\x12projectContextJson\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x0eVCSCredentials\x12\x19\n" +
	"\bvcs_type\x18\x01 \x01(\tR\avcsType\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x17\n" +
	"\assh_key\x18\x04 \x01(\tR\x06sshKey\"\x8c\x01\n" +
	"\x0eWorkflowConfig\x12;\n" +
	"\n" +
	"plan_steps\x18\x01 \x03(\v2\x1c.atlantis.agent.WorkflowStepR\tplanSteps\x12=\n" +
	"\vapply_steps\x18\x02 \x03(\v2\x1c.atlantis.agent.WorkflowStepR\n" +
	"applySteps\"\xd6\x01\n" +
	"\fWorkflowStep\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x1f\n" +
	"\vrun_command\x18\x02 \x01(\tR\n" +
	"runCommand\x12J\n" +
	"\n" +
	"extra_args\x18\x03 \x03(\v2+.atlantis.agent.WorkflowStep.ExtraArgsEntryR\textraArgs\x1a<\n" +
	"\x0eExtraArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x0fJobStatusUpdate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\x0eagent_pod_name\x18\x03 \x01(\tR\fagentPodName\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"#\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x82\x01\n" +
	"\n" +
	"JobDetails\x12=\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1d.atlantis.agent.JobAssignmentR\n" +
	"assignment\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x0fSyncJobsRequest\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\"E\n" +
	"\x10SyncJobsResponse\x121\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1d.atlantis.agent.JobAssignmentR\x04jobs2\xbf\x02\n" +
	"\fAgentService\x12M\n" +
	"\n" +
	"StreamJobs\x12\x1c.atlantis.agent.AgentMessage\x1a\x1d.atlantis.agent.JobAssignment(\x010\x01\x12G\n" +
	"\x0fReportJobStatus\x12\x1f.atlantis.agent.JobStatusUpdate\x1a\x13.atlantis.agent.Ack\x12@\n" +
	"\x06GetJob\x12\x1a.atlantis.agent.JobRequest\x1a\x1a.atlantis.agent.JobDetails\x12U\n" +
	"\x10SyncAssignedJobs\x12\x1f.atlantis.agent.SyncJobsRequest\x1a .atlantis.agent.SyncJobsResponseB3Z1github.com/runatlantis/atlantis/server/core/protob\x06proto3"

var (
	file_proto_atlantis_agent_proto_rawDescOnce sync.Once
	file_proto_atlantis_agent_proto_rawDescData []byte
)

func file_proto_atlantis_agent_proto_rawDescGZIP() []byte {
	file_proto_atlantis_agent_proto_rawDescOnce.Do(func() {
		file_proto_atlantis_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atlantis_agent_proto_rawDesc), len(file_proto_atlantis_agent_proto_rawDesc)))
	})
	return file_proto_atlantis_agent_proto_rawDescData
}

var file_proto_atlantis_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_atlantis_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),     // 0: atlantis.agent.AgentMessage
	(*Registration)(nil),     // 1: atlantis.agent.Registration
	(*Heartbeat)(nil),        // 2: atlantis.agent.Heartbeat
	(*JobResult)(nil),        // 3: atlantis.agent.JobResult
	(*CapacityUpdate)(nil),   // 4: atlantis.agent.CapacityUpdate
	(*JobAssignment)(nil),    // 5: atlantis.agent.JobAssignment
	(*VCSCredentials)(nil),   // 6: atlantis.agent.VCSCredentials
	(*WorkflowConfig)(nil),   // 7: atlantis.agent.WorkflowConfig
	(*WorkflowStep)(nil),     // 8: atlantis.agent.WorkflowStep
	(*JobStatusUpdate)(nil),  // 9: atlantis.agent.JobStatusUpdate
	(*JobRequest)(nil),       // 10: atlantis.agent.JobRequest
	(*JobDetails)(nil),       // 11: atlantis.agent.JobDetails
	(*Ack)(nil),              // 12: atlantis.agent.Ack
	(*SyncJobsRequest)(nil),  // 13: atlantis.agent.SyncJobsRequest
	(*SyncJobsResponse)(nil), // 14: atlantis.agent.SyncJobsResponse
	nil,                      // 15: atlantis.agent.Registration.LabelsEntry
	nil,                      // 16: atlantis.agent.JobAssignment.EnvVarsEntry
	nil,                      // 17: atlantis.agent.JobAssignment.MetadataEntry
	nil,                      // 18: atlantis.agent.WorkflowStep.ExtraArgsEntry
}
var file_proto_atlantis_agent_proto_depIdxs = []int32{
	1,  // 0: atlantis.agent.AgentMessage.registration:type_name -> atlantis.agent.Registration
	2,  // 1: atlantis.agent.AgentMessage.heartbeat:type_name -> atlantis.agent.Heartbeat
	3,  // 2: atlantis.agent.AgentMessage.job_result:type_name -> atlantis.agent.JobResult
	4,  // 3: atlantis.agent.AgentMessage.capacity_update:type_name -> atlantis.agent.CapacityUpdate
	15, // 4: atlantis.agent.Registration.labels:type_name -> atlantis.agent.Registration.LabelsEntry
	6,  // 5: atlantis.agent.JobAssignment.vcs_credentials:type_name -> atlantis.agent.VCSCredentials
	16, // 6: atlantis.agent.JobAssignment.env_vars:type_name -> atlantis.agent.JobAssignment.EnvVarsEntry
	7,  // 7: atlantis.agent.JobAssignment.workflow:type_name -> atlantis.agent.WorkflowConfig
	17, // 8: atlantis.agent.JobAssignment.metadata:type_name -> atlantis.agent.JobAssignment.MetadataEntry
	8,  // 9: atlantis.agent.WorkflowConfig.plan_steps:type_name -> atlantis.agent.WorkflowStep
	8,  // 10: atlantis.agent.WorkflowConfig.apply_steps:type_name -> atlantis.agent.WorkflowStep
	18, // 11: atlantis.agent.WorkflowStep.extra_args:type_name -> atlantis.agent.WorkflowStep.ExtraArgsEntry
	5,  // 12: atlantis.agent.JobDetails.assignment:type_name -> atlantis.agent.JobAssignment
	5,  // 13: atlantis.agent.SyncJobsResponse.jobs:type_name -> atlantis.agent.JobAssignment
	0,  // 14: atlantis.agent.AgentService.StreamJobs:input_type -> atlantis.agent.AgentMessage
	9,  // 15: atlantis.agent.AgentService.ReportJobStatus:input_type -> atlantis.agent.JobStatusUpdate
	10, // 16: atlantis.agent.AgentService.GetJob:input_type -> atlantis.agent.JobRequest
	13, // 17: atlantis.agent.AgentService.SyncAssignedJobs:input_type -> atlantis.agent.SyncJobsRequest
	5,  // 18: atlantis.agent.AgentService.StreamJobs:output_type -> atlantis.agent.JobAssignment
	12, // 19: atlantis.agent.AgentService.ReportJobStatus:output_type -> atlantis.agent.Ack
	11, // 20: atlantis.agent.AgentService.GetJob:output_type -> atlantis.agent.JobDetails
	14, // 21: atlantis.agent.AgentService.SyncAssignedJobs:output_type -> atlantis.agent.SyncJobsResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_atlantis_agent_proto_init() }
func file_proto_atlantis_agent_proto_init() {
	if File_proto_atlantis_agent_proto != nil {
		return
	}
	file_proto_atlantis_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Registration)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_JobResult)(nil),
		(*AgentMessage_CapacityUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atlantis_agent_proto_rawDesc), len(file_proto_atlantis_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atlantis_agent_proto_goTypes,
		DependencyIndexes: file_proto_atlantis_agent_proto_depIdxs,
		MessageInfos:      file_proto_atlantis_agent_proto_msgTypes,
	}.Build()
	File_proto_atlantis_agent_proto = out.File
	file_proto_atlantis_agent_proto_goTypes = nil
	file_proto_atlantis_agent_proto_depIdxs = nil
}
